from __future__ import annotations

import argparse
from pathlib import Path
import sys

import pandas as pd

sys.path.append(str(Path(__file__).resolve().parents[1]))

from src.evaluation.ragas_evaluator import evaluate_reference_free_with_ragas
from src.utils.io import load_json


def _run_to_dataset(run_file: str | Path) -> pd.DataFrame:
    run_data = load_json(run_file)
    contexts = [item.get("text", "") for item in run_data.get("retrieved", [])]
    return pd.DataFrame(
        [
            {
                "question": run_data.get("question", ""),
                "answer": run_data.get("answer", ""),
                "retrieved_contexts": contexts,
            }
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Evaluate a saved RAG run with reference-free RAGAS metrics"
    )
    parser.add_argument("run_file", help="Path to a JSON file generated by a RAG pipeline")
    parser.add_argument("--output", default="outputs/reports/reference_free_eval")
    args = parser.parse_args()

    result = evaluate_reference_free_with_ragas(_run_to_dataset(args.run_file), args.output)
    print(result["summary"])


if __name__ == "__main__":
    main()